### ISSUE TITLE
Little documentation in ServerCreate

### ISSUE THREAD

**Issue by Icemantheditor** [Scordo/TS3QueryLib.Net#11]
Hello, I'm trying to use the EditServer and CreateServer but I am not sure what parameters to feed it, I have many more questions and would love some documentation for these commands and more.

**Comment by Scordo** [comment]
Hello,

most of the functions are named equally to the ones in the official documentation:

http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

So please have a look at the official documentation.

Regards,
Scordo
