### ISSUE TITLE
Use async/await pattern

### ISSUE THREAD

**Issue by MaitreDede** [Scordo/TS3QueryLib.Net#13]
Hi,

Do you think you can make your lib use Tasks, to use the async/await pattern, and use if through all layers ? I would like to use your wonderfull lib in a framework 4.5 application that heavily relies on tasks scheduling...
I think you can either extend socket : http://blogs.msdn.com/b/pfxteam/archive/2011/12/15/10248293.aspx
Or use the TcpClient/NetworkStream that already hasasync task methods : https://msdn.microsoft.com/fr-fr/library/system.net.sockets.tcpclient(v=vs.110).aspx

Thanks :)

**Comment by Scordo** [comment]
Hi Maitre,

it is not possible for the current library. But I did it for the ".Net Core" version of the library.

Regards,
Scordo
