### ISSUE TITLE
ConnectionReset after a while

### ISSUE THREAD

**Issue by Yoiink** [Scordo/TS3QueryLib.Net#14]
I am getting this with the application I wrote, however I tried the console sample and it also disconnects after a while (seems to be exactly 10 minutes).

**Comment by FireEmerald** [comment]
Thats the normal behavior. If you would like to keep the connection established, just sent a keep-alive command like `version`.

**Comment by Yoiink** [comment]
Okay thanks, I wasn't sure if it was supposed to timeout or not. I've done what you suggested and perform a `GetVersion` every 5 minutes.
