### ISSUE TITLE
ServerCreateSnapshot failure

### ISSUE THREAD

**Issue by madman2021** [Scordo/TS3QueryLib.Net#15]
Teamspeak Log reports connection lost but the library simply doesn't return. Get's locked in the loop here
https://github.com/Scordo/TS3QueryLib.Net/blob/master/TS3QueryLib.Core.Silverlight/AsyncTcpDispatcher.cs#L457

Maybe something to do with the speed in which the request is processed as it only fails with a larger server. A brand new server still takes quite a long time to get a return... near enough instant with telnet of course.

**Comment by Scordo** [comment]
Hi, 

can you please validate this for the new release?:
https://ts3querylib.codeplex.com/releases/view/628874

Thanks!
Scordo
