### ISSUE TITLE
DeployServerSnapshot Not Working

### ISSUE THREAD

**Issue by HatipMevis** [Scordo/TS3QueryLib.Net#17]
ErrorId:1537
ErrorMessage:"invalid parameter count"
    public SimpleResponse DeployServerSnapshot(string snapshotData)
    {
      if (ExtensionMethods.IsNullOrTrimmedEmpty(snapshotData))
        throw new ArgumentException("snapshotData is null or trimmed empty", "snapshotData");
      Command command = CommandNameExtensions.CreateCommand(CommandName.ServerSnapshotDeploy);
      command.AddParameter(snapshotData);
      return ResponseBase<SimpleResponse>.Parse(this.SendCommand(command));
    }

**Comment by Scordo** [comment]
I'll have a look at it

**Comment by Scordo** [comment]
Fixed it. It will be included in the next release

**Comment by HatipMevis** [comment]
ty have a nice day
