### ISSUE TITLE
Struggling with the ChannelMessageRecieved Event

### ISSUE THREAD

**Issue by JackRyder** [Scordo/TS3QueryLib.Net#19]
Hi!

I'm really failing to understand for some reason the event for registering notifications for some reason. I've not put it inside a querydispatcher because I don't think that should make much of a difference. I'm also using 1 QueryRunner for all of my queries because I didn't think that'd make much of a difference. I'll provide code below, hope you can help me because I've been struggling for a few hours with this!

https://gist.github.com/JackRyder/e60f58696497a152ab43

**Comment by XoMEX** [comment]
You need to use AsyncTcpDispatcher as QueryDispatcher. The SyncTcpDispatcher doesen't support events.
Since you need to wait for AsyncTcpDispatcher.ReadyForSendingCommands event, you need to store it in a variable (which I would strongly suggest to handle disconnects/connection problems)

**Comment by JackRyder** [comment]
That fixed it, thanks so much! You're awesome for making this!
