### ISSUE TITLE
Using theese

### ISSUE THREAD

**Issue by SBreso** [Scordo/TS3QueryLib.Net#20]
Hi
I am a new dev. I would want that all my clients could speak ones with others inside the app. I want add this feature to my app. Can i do this with this api??

**Comment by FireEmerald** [comment]
There is none app expect the TeamSpeak 3 Client itself, which offers the opportunity to access the voice chat of TeamSpeak 3.

**Comment by SBreso** [comment]
ok, thanks. 
Then, can we connect to the ts3Server across ts3Client? and what more?

How we can use voice chat 'without' use ts3Client?
Thanks

**Comment by FireEmerald** [comment]
It's **not possible** to access the voice chat without the official ts3Client.

**Comment by SBreso** [comment]
thanks
