### ISSUE TITLE
GetClientDatabaseList only showing 200 users

### ISSUE THREAD

**Issue by JorenKoyen** [Scordo/TS3QueryLib.Net#21]
I'm trying to display all users in the database in my application but the list stops at 200 entries, which is not very convenient because the server I'm testing it on has 273 users in the database and database_ids going as high as 660. Is this an issue with the library or am I doing something wrong?

``` c#
foreach (var client in serverRunner.GetClientDatabaseList(1000))
{
    clientListbox.Items.Add(client.DatabaseId + " " + client.NickName);
}
```

**Comment by Scordo** [comment]
Hi,

sorry for the late response. 
Maybe the query limits the amount to a maximum of 200 entries per command.
Try this:

serverRunner.GetClientDatabaseList(0, 200, false);
serverRunner.GetClientDatabaseList(200, 200, false);
serverRunner.GetClientDatabaseList(400, 200, false);
...

Regards,
Scordo

**Comment by JorenKoyen** [comment]
Thanks for the response i'll try it out.

**Comment by Scordo** [comment]
Any results?

**Comment by Myszax** [comment]
clientdblist command can not respond more than 200 records even if you limit it more than this.
This is blocked by TS3 Server and won't be changed, I think.

**Comment by Scordo** [comment]
But paging like I suggested should work.
