### ISSUE TITLE
Incompatible with .NET Core

### ISSUE THREAD

**Issue by RulixQc** [Scordo/TS3QueryLib.Net#22]
I'd like to know if it'd be possible to get this librairy working with a .NET Core (without .NET Framework) project. Thank you!

**Comment by Scordo** [comment]
Hello,

the current library does not work with .net core. But I do have a week of time and I'm currently considering a complete rewrite in .net

Regards..

**Comment by Scordo** [comment]
I've started the new project here: https://github.com/Scordo/TS3QueryLib.Net.Core
It'll take some time to be feature complete. 
I think I'll only implement the server query and will skip the client query.
