### ISSUE TITLE
MoveClient .NET Doesn't allow for array of ClientID's

### ISSUE THREAD

**Issue by pythion** [Scordo/TS3QueryLib.Net#25]
CLIENTMOVE
Moves one or more clients specified with clid to the channel with ID cid. If the target channel has a password,
it needs to be specified with cpw. If the channel has no password, the parameter can be omitted.

Example:
clientmove clid=5|clid=6 cid=3

This would be useful for moving a lot of users at once.

**Comment by Scordo** [comment]
I've implemented it. Will be in the next released version.
