### ISSUE TITLE
Cannot catch any events

### ISSUE THREAD

**Issue by MisterSokol** [Scordo/TS3QueryLib.Net#27]
Hi again,

I have problem with event catching. I was trying to follow instructions from TS3 forum and from [http://ts3querylib.codeplex.com/SourceControl/changeset/view/59138#1119306](url) but nothing worked.
Here is my simplified code how I try to track notifications.

```
        public static void Event_Event(object sender, ClientMovedEventArgs e)
        {
            Console.WriteLine("I'M HERE");

        }

        private void Connect()
        {
            QueryDispatcher = new AsyncTcpDispatcher(ServerAddress, Port);
            QueryDispatcher.BanDetected += QueryDispatcher_BanDetected;
            QueryDispatcher.ReadyForSendingCommands += QueryDispatcher_ReadyForSendingCommands;
            QueryDispatcher.ServerClosedConnection += QueryDispatcher_ServerClosedConnection;
            QueryDispatcher.SocketError += QueryDispatcher_SocketError;

            QueryRunner = new QueryRunner(QueryDispatcher);
            QueryRunner.RegisterForNotifications(ServerNotifyRegisterEvent.Server);
            QueryRunner.Notifications.ClientMoved += Event_Event;

            QueryDispatcher.Connect();
        }

        private void QueryDispatcher_ReadyForSendingCommands(object sender, System.EventArgs e)
        {
            QueryRunner.Login(admin, pass);
            QueryRunner.SelectVirtualServerByPort(serverPort);
        }
```

Here is example for moving from channel to channel. No idea what could be wrong. I'm for sure connected to server because I check it by sending a poke command and I see my query client in server also.

**Comment by XoMEX** [comment]
You don't listen for the right Events. You have to listen to channel and either specify specific channel ids or channelid 0. The official documentation isn't really complete, but I found a (german) explanation on the [yatqa site](http://yat.qa/ressourcen/server-query-notify/)
The most important part there is the "Inhaltsverzeichnis" (Table of Contents), where you can see wich event notification raises wich events.
If you encounter further problems with this API I'd recommend opening a telnet connection (e.g. with Putty) ant trying the commands by hand and see if the error occures there. Alternatively you can sniff the traffic if you don't want to do it all by hand.

**Comment by MisterSokol** [comment]
Thanks for your answer XoMEX!

I've tried to fix it by changing the arguments of **RegisterForNotifications**:

> 1. (ServerNotifyRegisterEvent.Server, 0)
> 2. (ServerNotifyRegisterEvent.Server, null)
> 3. (ServerNotifyRegisterEvent.Channel, 0)
> 4. (ServerNotifyRegisterEvent.Channel, null)

None of those has worked for me...
Any more ideas?
Maybe I'm writing it in a wrong order or something? Could you provide your working example?

**Comment by XoMEX** [comment]
Just saw you Register for notifications before the QueryDispatcher is ready for sending commands, or logging in or selecting a server id.
Register for notifications is a Command, just as login, and thus can only be sent, when the querydispatcher is ready for sending commands. In addition you need to have a server instance selected and have some rights on that instance (login needed normally).
Furthermore, **always** check the return value of RegisterForNotifications (or other commands) for IsErroneous (should be false) and if that's true, check the ErrorMessage and somehow log it or present it to the user. (Or, as I said, do everything manually via telnet or sniff the traffic to find errors, helped me quiet often)

So to get it working do something like this (extended Samples/Console):

        private void QueryDispatcher_ReadyForSendingCommands(object sender, System.EventArgs e)
        {
            // you can only run commands on the queryrunner when this event has been raised first!
            QueryRunner = new QueryRunner(QueryDispatcher);

            VersionResponse versionResponse = QueryRunner.GetVersion();

            if (versionResponse.IsErroneous)
            {
                Console.WriteLine("Could not get server version: " + versionResponse.ErrorMessage);
                return;
            }

            Console.WriteLine("Server version:\n\nPlatform: {0}\nVersion: {1}\nBuild: {2}", versionResponse.Platform, versionResponse.Version, versionResponse.Build);
            
            //Important stuff begins here
            Console.WriteLine("Select Instance: " + !QueryRunner.Login("serveradmin", "pwd").IsErroneous);
            Console.WriteLine("Select Instance: " + !QueryRunner.SelectVirtualServerByPort(9987).IsErroneous);
            QueryRunner.Notifications.ClientMoved += Notifications_ClientMoved;
            Console.WriteLine("Register for Channelnotifications: " + !QueryRunner.RegisterForNotifications(TS3QueryLib.Core.Server.Entities.ServerNotifyRegisterEvent.Channel, 0).IsErroneous);
        }

**Comment by MisterSokol** [comment]
Thank you very much, it works now! The problem was with order which I thought I was setting right. Thanks again
