### ISSUE TITLE
IconId in ChannelEditedEventArgs  missing

### ISSUE THREAD

**Issue by I-MrFixIt-I** [Scordo/TS3QueryLib.Net#28]
Hello together,
it seems that your are missing the channel_icon_id in ChannelEditedEventArgs in the notifychanneledited event, see example.

Example:

- servernotifyregister event=channel id=0
- error id=0 msg=ok
- notifychannelcreated cid=17 cpid=0 channel_name=Test channel_codec_quality=6 channel_order=1 channel_flag_permanent=1 channel_codec_is_unencrypted=1 channel_flag_maxfamilyclients_unlimited=0 channel_flag_maxfamilyclients_inherited=1 invokerid=4 invokername=MrFixIt invokeruid=some_Random_uid
- notifychanneledited cid=17 reasonid=10 invokerid=4 invokername=MrFixIt invokeruid=some_Random_uid channel_icon_id=300
- notifychanneledited cid=17 reasonid=10 invokerid=4 invokername=MrFixIt invokeruid=some_Random_uid channel_icon_id=500

**Comment by Scordo** [comment]
Thanks :-)
