### ISSUE TITLE
Client Query?

### ISSUE THREAD

**Issue by felixosth** [Scordo/TS3QueryLib.Net#30]
Hi, good job on the lib. I'm searching for a good way to access the client query easily. 
I've tried to accomplish this on my own but with very poor progress so far. I checked the sample client query project out but it's very outdated. Now TS3 requires a authentication key to access commands.

Could you make a client query update? Would really save my month!

**Comment by Scordo** [comment]
Hi Felix,

can you point me to the documentation? I dont have much time, but I'll have a look at it.

**Comment by felixosth** [comment]
Thanks!
Here's the patch notes announcing the new authentication system:
http://forum.teamspeak.com/threads/130474

That means you have to use the cmd
auth apikey=xxxxx
after connecting to access all cmd's.

"Note you can also get documentation interactively, just connect your telnet client to localhost port 25639, and use "help" and "help <command>"."

http://forum.teamspeak.com/threads/66509-Official-ClientQuery-Plugin

**Comment by Scordo** [comment]
Mhh my Teamspeak Client (3.1.4) with Client Query Plugin installed and activated does not listen on port 25639. I cant get client query to work with my Teamspeak Client °_°. Any ideas? I cant develop anything if I can't test it ;-)

**Comment by felixosth** [comment]
Sure, I have the same client version and ClientQuery version 1.3. Are you
sure you have the right ClientQuery version?

Anyways, I just connect to that port with telnet and it works.

2017-06-22 16:47 GMT+02:00 Scordo <notifications@github.com>:

**Comment by Scordo** [comment]
I've published a new release:
https://github.com/Scordo/TS3QueryLib.Net/releases/tag/1.2.1.0

The QueryRunner now has a new Method "Authenticate" which you can use.

**Comment by felixosth** [comment]
Oh cool! Thank you!
