### ISSUE TITLE
ChannelDeleted Event raised once even if you delete more than one at same time

### ISSUE THREAD

**Issue by Myszax** [Scordo/TS3QueryLib.Net#32]
ChannelDeletedEventArgs has no list with deleted channels.
Example if you delete channel with sub-channels in it, you will only receive event from last sub channel deleted. There is no information about other sub-channels and their parent.

When I delete one channel with no sub-channels, there is no problem and server respond looks like:
`invokerid=2 invokername=adminName invokeruid=sOm31n7oK3ru1dxD= cid=29363`

When I delete channel with sub-channels inside, respond will look like:
`invokerid=2 invokername=adminName invokeruid=sOm31n7oK3ru1dxD= cid=25177|cid=25178|cid=25179|cid=25180|cid=25181|cid=25182|cid=25183|cid=25184|cid=25176`

There is a problem with handling this :(

**Comment by Scordo** [comment]
This is fixed in version 1.2.2.0. 
There is an additional property "SubChannelIdList" on the event arg.
