### ISSUE TITLE
AddMessage from Server, for sending offline message

### ISSUE THREAD

**Issue by Amit-B** [Scordo/TS3QueryLib.Net#36]
This method has a unique-client-id parameter of type int, which should be string.

**Comment by XoMEX** [comment]
As you can see in the TS3 Server Query Documentation[1] the internal command is called `MESSAGEADD`.

Searching this repo for that name and you'll find this method
```C#
        /// <summary>
        /// Sends an offline message to the client specified by cluid
        /// </summary>
        /// <param name="clientUniqueId">the unique id of the receiver</param>
        /// <param name="subject">the subject</param>
        /// <param name="message">the message</param>
        public SimpleResponse AddMessage(uint clientUniqueId, string subject, string message)
```

[1]http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

**Comment by Amit-B** [comment]
Hi. I did that already and I have sent offline messages by copying the same method with a change of the parameter type. I've just posted the issue so this can be fixed as the method with int parameter can't really be used.

**Comment by XoMEX** [comment]
yep, that's a problem. Then your wording wasn't quiet clear to me.

A better way to propose this change would be a pull request. Then I guess wait for @Scordo

**Comment by Scordo** [comment]
I see, the signature is wrong. I'll fix it

**Comment by TimmKroe** [comment]
Is it fixed now ?

**Comment by TimmKroe** [comment]
Merged & Fixed
